[package]
authors = ["Michael Barber <60610888+mike-barber@users.noreply.github.com>"]
edition = "2018"
name = "day16"
version = "0.1.0"

[dependencies]
lazy_static = "1.4"
regex = "1.4"
anyhow = "1.0"